variables:
  DOCKER_DRIVER: overlay2

stages:
- build

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  script:
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec*.tar.gz SOURCES
    - rpmbuild -ba libradsec.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  script:
    - sed -i "s/DIST/$CI_JOB_NAME/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.debian9common: &debian9common
  stage: build
  except:
    - tags
  script:
    # Rebuild libevent with ssl1.0
    - apt-get -y update && apt-get -y dist-upgrade
    - echo "deb-src $SRC_REPO" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source -y libevent"
    - cd libevent-$VERSION
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - mv ../*.deb ../../
    - cd ..
    - git clean -xdf
    # libradsec build
    - sed -i "s/DIST/$CI_JOB_NAME/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  script:
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/*/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  variables:
    SRC_REPO: http://deb.debian.org/debian stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  variables:
    SRC_REPO: http://archive.raspbian.org/raspbian/ stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common
  tags:
    - arm

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  <<: *debiancommon
  tags:
    - arm

debian11:
  image: $DOCKER_REGISTRY_URL/debian11:latest
  <<: *debiancommon

raspbian11:
  image: $DOCKER_REGISTRY_URL/raspbian11:latest
  <<: *debiancommon
  tags:
    - arm

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  variables:
    SRC_REPO: http://archive.ubuntu.com/ubuntu/ bionic main restricted
    VERSION: 2.1.8-stable
  <<: *debian9common

ubuntu20:
  image: $DOCKER_REGISTRY_URL/ubuntu20:latest
  <<: *debiancommon

alpine313:
  image: $DOCKER_REGISTRY_URL/alpine313:latest
  <<: *alpinecommon

alpine313_armhf:
  image: $DOCKER_REGISTRY_URL/alpine313_arm:latest
  <<: *alpinecommon
  tags:
    - arm

alpine315:
  image: $DOCKER_REGISTRY_URL/alpine315:latest
  <<: *alpinecommon

alpine315_armhf:
  image: $DOCKER_REGISTRY_URL/alpine315_arm:latest
  <<: *alpinecommon
  tags:
    - arm
