variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - yum -y upgrade
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" libradsec.spec.in
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec*.tar.gz SOURCES
    - rpmbuild -bb libradsec.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - apt-get -y update && apt-get -y dist-upgrade
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - autoreconf -fi
    - ./configure
    - make dist
    - mv libradsec-1.0.1.tar.gz ../libradsec_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*.deb

.debian9common: &debian9common
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    # Rebuild libevent with ssl1.0
    - echo "deb-src $SRC_REPO" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source -y libevent"
    - cd libevent-$VERSION
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot$CI_PIPELINE_ID "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - cp ../*.deb ../../
    - cd ..
    - git clean -xdf
    # libradsec build
    - apt-get -y update && apt-get -y dist-upgrade
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - autoreconf -fi
    - ./configure
    - make dist
    - mv libradsec-1.0.1.tar.gz ../libradsec_1.0.1.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*.deb

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/pkgrel=0/pkgrel=$CI_PIPELINE_ID/g" APKBUILD.in
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/moonshot/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  <<: *centoscommon

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  <<: *centoscommon

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  <<: *debiancommon

raspbian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/raspbian8:latest
  when: manual
  <<: *debiancommon

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  variables:
    SRC_REPO: http://deb.debian.org/debian stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

raspbian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/raspbian9:latest
  when: manual
  variables:
    SRC_REPO: http://archive.raspbian.org/raspbian/ stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

debian10:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian10:latest
  <<: *debiancommon

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  <<: *debiancommon

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  variables:
    SRC_REPO: http://archive.ubuntu.com/ubuntu/ bionic main restricted
    VERSION: 2.1.8-stable
  <<: *debian9common

alpine38:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/alpine38:latest
  <<: *alpinecommon

alpine38_armhf:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/alpine38_arm:latest
  when: manual
  <<: *alpinecommon
