variables:
  DOCKER_DRIVER: overlay2

stages:
- build

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" libradsec.spec.in
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec*.tar.gz SOURCES
    - rpmbuild -ba libradsec.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.debian9common: &debian9common
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    # Rebuild libevent with ssl1.0
    - echo "deb-src $SRC_REPO" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source -y libevent"
    - cd libevent-$VERSION
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot$CI_PIPELINE_ID "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - mv ../*.deb ../../
    - cd ..
    - git clean -xdf
    # libradsec build
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - debuild -us -uc
    - mkdir build
    - mv ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - cp $APKBUILD APKBUILD.in
    - sed -i "s/pkgrel=0/pkgrel=$CI_PIPELINE_ID/g" APKBUILD.in
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - sh autogen.sh
    - sed -i "s/GZIP_ENV = --best//g" Makefile.in
    - ./configure
    - make dist
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - mkdir apks
    - mv /home/tmpuser/packages/moonshot/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos6:
  image: $DOCKER_REGISTRY_URL/centos6:latest
  <<: *centoscommon

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian8:
  image: $DOCKER_REGISTRY_URL/debian8:latest
  <<: *debiancommon

raspbian8:
  image: $DOCKER_REGISTRY_URL/raspbian8:latest
  when: manual
  <<: *debiancommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  variables:
    SRC_REPO: http://deb.debian.org/debian stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

raspbian9:
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  when: manual
  variables:
    SRC_REPO: http://archive.raspbian.org/raspbian/ stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian10:
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  when: manual
  <<: *debiancommon

ubuntu16:
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  variables:
    SRC_REPO: http://archive.ubuntu.com/ubuntu/ bionic main restricted
    VERSION: 2.1.8-stable
  <<: *debian9common

alpine38:
  image: $DOCKER_REGISTRY_URL/alpine38:latest
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine38_armhf:
  image: $DOCKER_REGISTRY_URL/alpine38_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine38
  <<: *alpinecommon

alpine39:
  image: $DOCKER_REGISTRY_URL/alpine39:latest
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon

alpine39_armhf:
  image: $DOCKER_REGISTRY_URL/alpine39_arm:latest
  when: manual
  variables:
    APKBUILD: APKBUILD.in.alpine39
  <<: *alpinecommon
