variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" libradsec.spec.in
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec*.tar.gz SOURCES
    - rpmbuild -bb libradsec.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  stage: build
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" libradsec.spec.in
    - autoreconf -fi
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec-*.tar.gz SOURCES
    - rpmbuild -bb libradsec.spec --define "_topdir `pwd`"
  artifacts:
    paths:
        - RPMS

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  stage: build
  tags:
    - moonshot
  script:
    # Rebuild libevent with ssl1.0
    - echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source libevent"
    - cd libevent-2.1.8-stable
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - cp ../*.deb ../../
    - git clean -xdf
    # libradsec build
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  stage: build
  tags:
    - moonshot
  script:
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  stage: build
  tags:
    - moonshot
  script:
    # Rebuild libevent with ssl1.0
    - echo "deb-src http://archive.ubuntu.com/ubuntu/ bionic main restricted" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source libevent"
    - cd libevent-2.1.8-stable
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - cp ../*.deb ../../
    - git clean -xdf
    # libradsec build
    - dch -l "b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb
