variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

.centoscommon: &centoscommon
  stage: build
  tags:
    - moonshot
  script:
    - yum upgrade
    - sed -i "s/\(.\)%{?dist}/\1b$CI_PIPELINE_ID%{?dist}/g" libradsec.spec.in
    - sh autogen.sh
    - ./configure
    - make dist
    - mkdir -p SOURCES
    - mv libradsec*.tar.gz SOURCES
    - rpmbuild -bb libradsec.spec --define "_topdir `pwd`"
    - for i in RPMS/x86_64/*.rpm; do curl --user "$NEXUS_USER:$NEXUS_PWD" -f --upload-file "$i"  https://nexus.ci.ti.ja.net/repository/moonshot/$CI_JOB_NAME/; done
  artifacts:
    paths:
        - RPMS

.debiancommon: &debiancommon
  stage: build
  tags:
    - moonshot
  script:
    - apt-get -y update && apt-get -y dist-upgrade
    - dch -l ".$CI_JOB_NAME.b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - make dist
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

.debian9common: &debian9common
  stage: build
  tags:
    - moonshot
  script:
    # Rebuild libevent with ssl1.0
    - echo "deb-src $SRC_REPO" >> /etc/apt/sources.list
    - apt-get update
    - useradd tmpuser
    - chown tmpuser .
    - su tmpuser -c "apt-get source -y libevent"
    - cd libevent-$VERSION
    - sed -i 's/libssl-dev/libssl1.0-dev/g' debian/control
    - dch -l moonshot "Build with OpenSSL 1.0"
    - debuild -us -uc
    - dpkg -i ../*.deb
    - cp ../*.deb ../../
    - cd ..
    - git clean -xdf
    # libradsec build
    - apt-get -y update && apt-get -y dist-upgrade
    - dch -l ".$CI_JOB_NAME.b$CI_PIPELINE_ID" "Include job ID"
    - autoreconf -fi
    - ./configure
    - PERL5LIB=. make dist
    - mv libradsec-0.0.5.tar.gz ../libradsec_0.0.5.orig.tar.gz
    - debuild -us -uc
    - mkdir build
    - cp ../*.deb build
  artifacts:
    paths:
        - build/*.deb

centos6:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos6:latest
  <<: *centoscommon

centos7:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/centos7:latest
  <<: *centoscommon

debian8:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian8:latest
  <<: *debiancommon

debian9:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/debian9:latest
  variables:
    SRC_REPO: http://deb.debian.org/debian stretch main
    VERSION: 2.0.21-stable
  <<: *debian9common

ubuntu14:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu14:latest
  <<: *debiancommon

ubuntu16:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: registry.ci.ti.ja.net/jisc/moonshot-build/ubuntu18:latest
  variables:
    SRC_REPO: http://archive.ubuntu.com/ubuntu/ bionic main restricted
    VERSION: 2.1.8-stable
  <<: *debian9common
